name: dio_retry
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/saileshbro/dio_retry

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
